name: Build Linux Only

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./YALCY

      - name: Build
        run: dotnet build --configuration Release
        working-directory: ./YALCY

      - name: Publish
        run: dotnet publish -c Release -r linux-x64 --self-contained=true --output ./publish
        working-directory: ./YALCY

      - name: Upload Linux Binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux-binaries
          path: ./YALCY/publish

  release:
    runs-on: ubuntu-latest
    needs: [build-linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine next version
        id: next_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          IFS='.' read -r major minor patch <<<"${latest_tag//v/}"
          new_patch=$((patch + 1))
          next_version="v$major.$minor.$new_patch"
          echo "next_version=$next_version" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.next_version }}
          release_name: "YALCY ${{ env.next_version }}"
          body: |
            Automatically generated release.
            Includes:
            - Linux x64 binaries
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Download Linux Binaries
        uses: actions/download-artifact@v4
        with:
          name: linux-binaries
          path: ./linux

      - name: Create Tarball for Linux Binaries
        run: |
          cd ./linux
          tar -czvf ../linux-x64-binaries.tar.gz .

      - name: Upload Linux Binaries to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux-x64-binaries.tar.gz
          asset_name: linux-x64-binaries.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
