name: Delete this

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore YALCY/YALCY.csproj

      - name: Build
        run: dotnet build --configuration Release YALCY/YALCY.csproj

      - name: Publish
        run: dotnet publish -c Release -r linux-x64 --self-contained=true --output ./publish YALCY/YALCY.csproj

      - name: Upload Linux Binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: YALCY/publish
